receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  jaeger:
    endpoint: "host.docker.internal:14250"
    tls:
        insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  telemetry:
    logs:
        level: "debug"
  extensions: 
    - health_check
  pipelines:
    traces:
      receivers: 
        - otlp
      exporters: 
        - jaeger
    metrics:
      receivers: 
        - otlp
      processors: 
        - batch
      exporters: 
        - prometheus